/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response Schema for AEX9 contract balances responses
 * @export
 * @interface Aex9ContractBalanceResponse
 */
export interface Aex9ContractBalanceResponse {
    /**
     * The wallet pubkey
     * @type {string}
     * @memberof Aex9ContractBalanceResponse
     */
    accountId: string;
    /**
     * The balance amount
     * @type {number}
     * @memberof Aex9ContractBalanceResponse
     */
    amount: number;
    /**
     * The block hash, indicating a state of a balance for that block
     * @type {number}
     * @memberof Aex9ContractBalanceResponse
     */
    blockHash: number;
    /**
     * The contract id of given token
     * @type {number}
     * @memberof Aex9ContractBalanceResponse
     */
    contractId: number;
    /**
     * The block height, indicating a state of a balance for that block height
     * @type {number}
     * @memberof Aex9ContractBalanceResponse
     */
    height: number;
    /**
     * The index of the event log that changed the balance
     * @type {number}
     * @memberof Aex9ContractBalanceResponse
     */
    lastLogIdx: number;
    /**
     * The hash of the last transaction that changed the balance
     * @type {string}
     * @memberof Aex9ContractBalanceResponse
     */
    lastTxHash: string;
}

/**
 * Check if a given object implements the Aex9ContractBalanceResponse interface.
 */
export function instanceOfAex9ContractBalanceResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "blockHash" in value;
    isInstance = isInstance && "contractId" in value;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "lastLogIdx" in value;
    isInstance = isInstance && "lastTxHash" in value;

    return isInstance;
}

export function Aex9ContractBalanceResponseFromJSON(json: any): Aex9ContractBalanceResponse {
    return Aex9ContractBalanceResponseFromJSONTyped(json, false);
}

export function Aex9ContractBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aex9ContractBalanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'amount': json['amount'],
        'blockHash': json['block_hash'],
        'contractId': json['contract_id'],
        'height': json['height'],
        'lastLogIdx': json['last_log_idx'],
        'lastTxHash': json['last_tx_hash'],
    };
}

export function Aex9ContractBalanceResponseToJSON(value?: Aex9ContractBalanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'amount': value.amount,
        'block_hash': value.blockHash,
        'contract_id': value.contractId,
        'height': value.height,
        'last_log_idx': value.lastLogIdx,
        'last_tx_hash': value.lastTxHash,
    };
}

