/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response Schema for AEX9 balance responses
 * @export
 * @interface Aex9BalanceResponse
 */
export interface Aex9BalanceResponse {
    /**
     * The account present on a AEX9
     * @type {string}
     * @memberof Aex9BalanceResponse
     */
    accountId: string;
    /**
     * The amount of AEX9 token
     * @type {number}
     * @memberof Aex9BalanceResponse
     */
    amount?: number;
    /**
     * The block hash, indicating a state of a balance for that block
     * @type {number}
     * @memberof Aex9BalanceResponse
     */
    blockHash: number;
    /**
     * The contract id of given token
     * @type {number}
     * @memberof Aex9BalanceResponse
     */
    contractId: number;
    /**
     * The block height, indicating a state of a balance for that block height
     * @type {number}
     * @memberof Aex9BalanceResponse
     */
    height?: number;
}

/**
 * Check if a given object implements the Aex9BalanceResponse interface.
 */
export function instanceOfAex9BalanceResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "blockHash" in value;
    isInstance = isInstance && "contractId" in value;

    return isInstance;
}

export function Aex9BalanceResponseFromJSON(json: any): Aex9BalanceResponse {
    return Aex9BalanceResponseFromJSONTyped(json, false);
}

export function Aex9BalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aex9BalanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'blockHash': json['block_hash'],
        'contractId': json['contract_id'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function Aex9BalanceResponseToJSON(value?: Aex9BalanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'amount': value.amount,
        'block_hash': value.blockHash,
        'contract_id': value.contractId,
        'height': value.height,
    };
}

