/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuctionInfoLastBid
 */
export interface AuctionInfoLastBid {
    /**
     * 
     * @type {string}
     * @memberof AuctionInfoLastBid
     */
    blockHash?: string;
    /**
     * 
     * @type {number}
     * @memberof AuctionInfoLastBid
     */
    blockHeight?: number;
    /**
     * 
     * @type {string}
     * @memberof AuctionInfoLastBid
     */
    hash?: string;
    /**
     * 
     * @type {number}
     * @memberof AuctionInfoLastBid
     */
    microIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof AuctionInfoLastBid
     */
    microTime?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuctionInfoLastBid
     */
    signatures?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof AuctionInfoLastBid
     */
    tx?: object;
}

/**
 * Check if a given object implements the AuctionInfoLastBid interface.
 */
export function instanceOfAuctionInfoLastBid(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuctionInfoLastBidFromJSON(json: any): AuctionInfoLastBid {
    return AuctionInfoLastBidFromJSONTyped(json, false);
}

export function AuctionInfoLastBidFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuctionInfoLastBid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blockHash': !exists(json, 'block_hash') ? undefined : json['block_hash'],
        'blockHeight': !exists(json, 'block_height') ? undefined : json['block_height'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'microIndex': !exists(json, 'micro_index') ? undefined : json['micro_index'],
        'microTime': !exists(json, 'micro_time') ? undefined : json['micro_time'],
        'signatures': !exists(json, 'signatures') ? undefined : json['signatures'],
        'tx': !exists(json, 'tx') ? undefined : json['tx'],
    };
}

export function AuctionInfoLastBidToJSON(value?: AuctionInfoLastBid | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'block_hash': value.blockHash,
        'block_height': value.blockHeight,
        'hash': value.hash,
        'micro_index': value.microIndex,
        'micro_time': value.microTime,
        'signatures': value.signatures,
        'tx': value.tx,
    };
}

