/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex141TemplateTokensResponse } from './Aex141TemplateTokensResponse';
import {
    Aex141TemplateTokensResponseFromJSON,
    Aex141TemplateTokensResponseFromJSONTyped,
    Aex141TemplateTokensResponseToJSON,
} from './Aex141TemplateTokensResponse';

/**
 * 
 * @export
 * @interface GetAex141TemplateTokens200ResponseAllOf
 */
export interface GetAex141TemplateTokens200ResponseAllOf {
    /**
     * 
     * @type {Array<Aex141TemplateTokensResponse>}
     * @memberof GetAex141TemplateTokens200ResponseAllOf
     */
    data?: Array<Aex141TemplateTokensResponse>;
}

/**
 * Check if a given object implements the GetAex141TemplateTokens200ResponseAllOf interface.
 */
export function instanceOfGetAex141TemplateTokens200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAex141TemplateTokens200ResponseAllOfFromJSON(json: any): GetAex141TemplateTokens200ResponseAllOf {
    return GetAex141TemplateTokens200ResponseAllOfFromJSONTyped(json, false);
}

export function GetAex141TemplateTokens200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAex141TemplateTokens200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex141TemplateTokensResponseFromJSON)),
    };
}

export function GetAex141TemplateTokens200ResponseAllOfToJSON(value?: GetAex141TemplateTokens200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex141TemplateTokensResponseToJSON)),
    };
}

