/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex9BalanceResponse } from './Aex9BalanceResponse';
import {
    Aex9BalanceResponseFromJSON,
    Aex9BalanceResponseFromJSONTyped,
    Aex9BalanceResponseToJSON,
} from './Aex9BalanceResponse';

/**
 * 
 * @export
 * @interface GetAex9ContractAccountBalanceHistory200Response
 */
export interface GetAex9ContractAccountBalanceHistory200Response {
    /**
     * 
     * @type {Array<Aex9BalanceResponse>}
     * @memberof GetAex9ContractAccountBalanceHistory200Response
     */
    data?: Array<Aex9BalanceResponse>;
    /**
     * 
     * @type {string}
     * @memberof GetAex9ContractAccountBalanceHistory200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAex9ContractAccountBalanceHistory200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetAex9ContractAccountBalanceHistory200Response interface.
 */
export function instanceOfGetAex9ContractAccountBalanceHistory200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAex9ContractAccountBalanceHistory200ResponseFromJSON(json: any): GetAex9ContractAccountBalanceHistory200Response {
    return GetAex9ContractAccountBalanceHistory200ResponseFromJSONTyped(json, false);
}

export function GetAex9ContractAccountBalanceHistory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAex9ContractAccountBalanceHistory200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex9BalanceResponseFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetAex9ContractAccountBalanceHistory200ResponseToJSON(value?: GetAex9ContractAccountBalanceHistory200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex9BalanceResponseToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

