/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex141TemplatesResponse } from './Aex141TemplatesResponse';
import {
    Aex141TemplatesResponseFromJSON,
    Aex141TemplatesResponseFromJSONTyped,
    Aex141TemplatesResponseToJSON,
} from './Aex141TemplatesResponse';

/**
 * 
 * @export
 * @interface GetAex141ContractTemplates200ResponseAllOf
 */
export interface GetAex141ContractTemplates200ResponseAllOf {
    /**
     * 
     * @type {Array<Aex141TemplatesResponse>}
     * @memberof GetAex141ContractTemplates200ResponseAllOf
     */
    data?: Array<Aex141TemplatesResponse>;
}

/**
 * Check if a given object implements the GetAex141ContractTemplates200ResponseAllOf interface.
 */
export function instanceOfGetAex141ContractTemplates200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAex141ContractTemplates200ResponseAllOfFromJSON(json: any): GetAex141ContractTemplates200ResponseAllOf {
    return GetAex141ContractTemplates200ResponseAllOfFromJSONTyped(json, false);
}

export function GetAex141ContractTemplates200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAex141ContractTemplates200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex141TemplatesResponseFromJSON)),
    };
}

export function GetAex141ContractTemplates200ResponseAllOfToJSON(value?: GetAex141ContractTemplates200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex141TemplatesResponseToJSON)),
    };
}

