/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Activity } from './Activity';
import {
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
} from './Activity';

/**
 * 
 * @export
 * @interface GetAccountActivities200Response
 */
export interface GetAccountActivities200Response {
    /**
     * 
     * @type {Array<Activity>}
     * @memberof GetAccountActivities200Response
     */
    data?: Array<Activity>;
    /**
     * 
     * @type {string}
     * @memberof GetAccountActivities200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountActivities200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetAccountActivities200Response interface.
 */
export function instanceOfGetAccountActivities200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAccountActivities200ResponseFromJSON(json: any): GetAccountActivities200Response {
    return GetAccountActivities200ResponseFromJSONTyped(json, false);
}

export function GetAccountActivities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountActivities200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ActivityFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetAccountActivities200ResponseToJSON(value?: GetAccountActivities200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ActivityToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

