/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex9TransferResponse } from './Aex9TransferResponse';
import {
    Aex9TransferResponseFromJSON,
    Aex9TransferResponseFromJSONTyped,
    Aex9TransferResponseToJSON,
} from './Aex9TransferResponse';

/**
 * 
 * @export
 * @interface GetAex9PairTransfers200Response
 */
export interface GetAex9PairTransfers200Response {
    /**
     * 
     * @type {Array<Aex9TransferResponse>}
     * @memberof GetAex9PairTransfers200Response
     */
    data?: Array<Aex9TransferResponse>;
    /**
     * 
     * @type {string}
     * @memberof GetAex9PairTransfers200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAex9PairTransfers200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetAex9PairTransfers200Response interface.
 */
export function instanceOfGetAex9PairTransfers200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAex9PairTransfers200ResponseFromJSON(json: any): GetAex9PairTransfers200Response {
    return GetAex9PairTransfers200ResponseFromJSONTyped(json, false);
}

export function GetAex9PairTransfers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAex9PairTransfers200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex9TransferResponseFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetAex9PairTransfers200ResponseToJSON(value?: GetAex9PairTransfers200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex9TransferResponseToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

