/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex9TransferResponse } from './Aex9TransferResponse';
import {
    Aex9TransferResponseFromJSON,
    Aex9TransferResponseFromJSONTyped,
    Aex9TransferResponseToJSON,
} from './Aex9TransferResponse';

/**
 * 
 * @export
 * @interface GetAex9PairTransfers200ResponseAllOf
 */
export interface GetAex9PairTransfers200ResponseAllOf {
    /**
     * 
     * @type {Array<Aex9TransferResponse>}
     * @memberof GetAex9PairTransfers200ResponseAllOf
     */
    data?: Array<Aex9TransferResponse>;
}

/**
 * Check if a given object implements the GetAex9PairTransfers200ResponseAllOf interface.
 */
export function instanceOfGetAex9PairTransfers200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAex9PairTransfers200ResponseAllOfFromJSON(json: any): GetAex9PairTransfers200ResponseAllOf {
    return GetAex9PairTransfers200ResponseAllOfFromJSONTyped(json, false);
}

export function GetAex9PairTransfers200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAex9PairTransfers200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex9TransferResponseFromJSON)),
    };
}

export function GetAex9PairTransfers200ResponseAllOfToJSON(value?: GetAex9PairTransfers200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex9TransferResponseToJSON)),
    };
}

