/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type GetBlockHashOrKbiParameter
 * 
 * @export
 */
export type GetBlockHashOrKbiParameter = number | string;

export function GetBlockHashOrKbiParameterFromJSON(json: any): GetBlockHashOrKbiParameter {
    return GetBlockHashOrKbiParameterFromJSONTyped(json, false);
}

export function GetBlockHashOrKbiParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlockHashOrKbiParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...numberFromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function GetBlockHashOrKbiParameterToJSON(value?: GetBlockHashOrKbiParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

