/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
} from './Block';

/**
 * 
 * @export
 * @interface GetBlocks200Response
 */
export interface GetBlocks200Response {
    /**
     * 
     * @type {Array<Block>}
     * @memberof GetBlocks200Response
     */
    data?: Array<Block>;
    /**
     * 
     * @type {string}
     * @memberof GetBlocks200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetBlocks200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetBlocks200Response interface.
 */
export function instanceOfGetBlocks200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetBlocks200ResponseFromJSON(json: any): GetBlocks200Response {
    return GetBlocks200ResponseFromJSONTyped(json, false);
}

export function GetBlocks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlocks200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(BlockFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetBlocks200ResponseToJSON(value?: GetBlocks200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(BlockToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

