/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Block } from './Block';
import {
    BlockFromJSON,
    BlockFromJSONTyped,
    BlockToJSON,
} from './Block';

/**
 * 
 * @export
 * @interface GetBlocks200ResponseAllOf
 */
export interface GetBlocks200ResponseAllOf {
    /**
     * 
     * @type {Array<Block>}
     * @memberof GetBlocks200ResponseAllOf
     */
    data?: Array<Block>;
}

/**
 * Check if a given object implements the GetBlocks200ResponseAllOf interface.
 */
export function instanceOfGetBlocks200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetBlocks200ResponseAllOfFromJSON(json: any): GetBlocks200ResponseAllOf {
    return GetBlocks200ResponseAllOfFromJSONTyped(json, false);
}

export function GetBlocks200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlocks200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(BlockFromJSON)),
    };
}

export function GetBlocks200ResponseAllOfToJSON(value?: GetBlocks200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(BlockToJSON)),
    };
}

