/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
} from './Channel';

/**
 * 
 * @export
 * @interface GetChannels200Response
 */
export interface GetChannels200Response {
    /**
     * 
     * @type {Array<Channel>}
     * @memberof GetChannels200Response
     */
    data?: Array<Channel>;
    /**
     * 
     * @type {string}
     * @memberof GetChannels200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetChannels200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetChannels200Response interface.
 */
export function instanceOfGetChannels200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetChannels200ResponseFromJSON(json: any): GetChannels200Response {
    return GetChannels200ResponseFromJSONTyped(json, false);
}

export function GetChannels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannels200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ChannelFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetChannels200ResponseToJSON(value?: GetChannels200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ChannelToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

