/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
} from './Channel';

/**
 * 
 * @export
 * @interface GetChannels200ResponseAllOf
 */
export interface GetChannels200ResponseAllOf {
    /**
     * 
     * @type {Array<Channel>}
     * @memberof GetChannels200ResponseAllOf
     */
    data?: Array<Channel>;
}

/**
 * Check if a given object implements the GetChannels200ResponseAllOf interface.
 */
export function instanceOfGetChannels200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetChannels200ResponseAllOfFromJSON(json: any): GetChannels200ResponseAllOf {
    return GetChannels200ResponseAllOfFromJSONTyped(json, false);
}

export function GetChannels200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChannels200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ChannelFromJSON)),
    };
}

export function GetChannels200ResponseAllOfToJSON(value?: GetChannels200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ChannelToJSON)),
    };
}

