/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeltaStat } from './DeltaStat';
import {
    DeltaStatFromJSON,
    DeltaStatFromJSONTyped,
    DeltaStatToJSON,
} from './DeltaStat';

/**
 * 
 * @export
 * @interface GetDeltastats200Response
 */
export interface GetDeltastats200Response {
    /**
     * 
     * @type {Array<DeltaStat>}
     * @memberof GetDeltastats200Response
     */
    data?: Array<DeltaStat>;
    /**
     * 
     * @type {string}
     * @memberof GetDeltastats200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetDeltastats200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetDeltastats200Response interface.
 */
export function instanceOfGetDeltastats200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetDeltastats200ResponseFromJSON(json: any): GetDeltastats200Response {
    return GetDeltastats200ResponseFromJSONTyped(json, false);
}

export function GetDeltastats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeltastats200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(DeltaStatFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetDeltastats200ResponseToJSON(value?: GetDeltastats200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(DeltaStatToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

