/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MicroBlock } from './MicroBlock';
import {
    MicroBlockFromJSON,
    MicroBlockFromJSONTyped,
    MicroBlockToJSON,
} from './MicroBlock';

/**
 * 
 * @export
 * @interface GetKeyBlockMicroBlocks200Response
 */
export interface GetKeyBlockMicroBlocks200Response {
    /**
     * 
     * @type {Array<MicroBlock>}
     * @memberof GetKeyBlockMicroBlocks200Response
     */
    data?: Array<MicroBlock>;
    /**
     * 
     * @type {string}
     * @memberof GetKeyBlockMicroBlocks200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetKeyBlockMicroBlocks200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetKeyBlockMicroBlocks200Response interface.
 */
export function instanceOfGetKeyBlockMicroBlocks200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetKeyBlockMicroBlocks200ResponseFromJSON(json: any): GetKeyBlockMicroBlocks200Response {
    return GetKeyBlockMicroBlocks200ResponseFromJSONTyped(json, false);
}

export function GetKeyBlockMicroBlocks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKeyBlockMicroBlocks200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(MicroBlockFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetKeyBlockMicroBlocks200ResponseToJSON(value?: GetKeyBlockMicroBlocks200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(MicroBlockToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

