/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KeyBlock } from './KeyBlock';
import {
    KeyBlockFromJSON,
    KeyBlockFromJSONTyped,
    KeyBlockToJSON,
} from './KeyBlock';

/**
 * 
 * @export
 * @interface GetKeyBlocks200ResponseAllOf
 */
export interface GetKeyBlocks200ResponseAllOf {
    /**
     * 
     * @type {Array<KeyBlock>}
     * @memberof GetKeyBlocks200ResponseAllOf
     */
    data?: Array<KeyBlock>;
}

/**
 * Check if a given object implements the GetKeyBlocks200ResponseAllOf interface.
 */
export function instanceOfGetKeyBlocks200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetKeyBlocks200ResponseAllOfFromJSON(json: any): GetKeyBlocks200ResponseAllOf {
    return GetKeyBlocks200ResponseAllOfFromJSONTyped(json, false);
}

export function GetKeyBlocks200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKeyBlocks200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(KeyBlockFromJSON)),
    };
}

export function GetKeyBlocks200ResponseAllOfToJSON(value?: GetKeyBlocks200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(KeyBlockToJSON)),
    };
}

