/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MicroBlock } from './MicroBlock';
import {
    MicroBlockFromJSON,
    MicroBlockFromJSONTyped,
    MicroBlockToJSON,
} from './MicroBlock';

/**
 * 
 * @export
 * @interface GetKeyBlockMicroBlocks200ResponseAllOf
 */
export interface GetKeyBlockMicroBlocks200ResponseAllOf {
    /**
     * 
     * @type {Array<MicroBlock>}
     * @memberof GetKeyBlockMicroBlocks200ResponseAllOf
     */
    data?: Array<MicroBlock>;
}

/**
 * Check if a given object implements the GetKeyBlockMicroBlocks200ResponseAllOf interface.
 */
export function instanceOfGetKeyBlockMicroBlocks200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetKeyBlockMicroBlocks200ResponseAllOfFromJSON(json: any): GetKeyBlockMicroBlocks200ResponseAllOf {
    return GetKeyBlockMicroBlocks200ResponseAllOfFromJSONTyped(json, false);
}

export function GetKeyBlockMicroBlocks200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKeyBlockMicroBlocks200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(MicroBlockFromJSON)),
    };
}

export function GetKeyBlockMicroBlocks200ResponseAllOfToJSON(value?: GetKeyBlockMicroBlocks200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(MicroBlockToJSON)),
    };
}

