/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KeyBlock } from './KeyBlock';
import {
    KeyBlockFromJSON,
    KeyBlockFromJSONTyped,
    KeyBlockToJSON,
} from './KeyBlock';

/**
 * 
 * @export
 * @interface GetKeyBlocks200Response
 */
export interface GetKeyBlocks200Response {
    /**
     * 
     * @type {Array<KeyBlock>}
     * @memberof GetKeyBlocks200Response
     */
    data?: Array<KeyBlock>;
    /**
     * 
     * @type {string}
     * @memberof GetKeyBlocks200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetKeyBlocks200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetKeyBlocks200Response interface.
 */
export function instanceOfGetKeyBlocks200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetKeyBlocks200ResponseFromJSON(json: any): GetKeyBlocks200Response {
    return GetKeyBlocks200ResponseFromJSONTyped(json, false);
}

export function GetKeyBlocks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKeyBlocks200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(KeyBlockFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetKeyBlocks200ResponseToJSON(value?: GetKeyBlocks200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(KeyBlockToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

