/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNamePointees200Response
 */
export interface GetNamePointees200Response {
    /**
     * 
     * @type {object}
     * @memberof GetNamePointees200Response
     */
    active?: object;
    /**
     * 
     * @type {object}
     * @memberof GetNamePointees200Response
     */
    inactive?: object;
}

/**
 * Check if a given object implements the GetNamePointees200Response interface.
 */
export function instanceOfGetNamePointees200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNamePointees200ResponseFromJSON(json: any): GetNamePointees200Response {
    return GetNamePointees200ResponseFromJSONTyped(json, false);
}

export function GetNamePointees200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNamePointees200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'inactive': !exists(json, 'inactive') ? undefined : json['inactive'],
    };
}

export function GetNamePointees200ResponseToJSON(value?: GetNamePointees200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'inactive': value.inactive,
    };
}

