/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Name } from './Name';
import {
    NameFromJSON,
    NameFromJSONTyped,
    NameToJSON,
} from './Name';

/**
 * 
 * @export
 * @interface GetNames200ResponseAllOf
 */
export interface GetNames200ResponseAllOf {
    /**
     * 
     * @type {Array<Name>}
     * @memberof GetNames200ResponseAllOf
     */
    data?: Array<Name>;
}

/**
 * Check if a given object implements the GetNames200ResponseAllOf interface.
 */
export function instanceOfGetNames200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNames200ResponseAllOfFromJSON(json: any): GetNames200ResponseAllOf {
    return GetNames200ResponseAllOfFromJSONTyped(json, false);
}

export function GetNames200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNames200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(NameFromJSON)),
    };
}

export function GetNames200ResponseAllOfToJSON(value?: GetNames200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(NameToJSON)),
    };
}

