/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Name } from './Name';
import {
    NameFromJSON,
    NameFromJSONTyped,
    NameToJSON,
} from './Name';

/**
 * 
 * @export
 * @interface GetNames200Response
 */
export interface GetNames200Response {
    /**
     * 
     * @type {Array<Name>}
     * @memberof GetNames200Response
     */
    data?: Array<Name>;
    /**
     * 
     * @type {string}
     * @memberof GetNames200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetNames200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetNames200Response interface.
 */
export function instanceOfGetNames200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNames200ResponseFromJSON(json: any): GetNames200Response {
    return GetNames200ResponseFromJSONTyped(json, false);
}

export function GetNames200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNames200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(NameFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetNames200ResponseToJSON(value?: GetNames200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(NameToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

