/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Oracle } from './Oracle';
import {
    OracleFromJSON,
    OracleFromJSONTyped,
    OracleToJSON,
} from './Oracle';

/**
 * 
 * @export
 * @interface GetOracles200ResponseAllOf
 */
export interface GetOracles200ResponseAllOf {
    /**
     * 
     * @type {Array<Oracle>}
     * @memberof GetOracles200ResponseAllOf
     */
    data?: Array<Oracle>;
}

/**
 * Check if a given object implements the GetOracles200ResponseAllOf interface.
 */
export function instanceOfGetOracles200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetOracles200ResponseAllOfFromJSON(json: any): GetOracles200ResponseAllOf {
    return GetOracles200ResponseAllOfFromJSONTyped(json, false);
}

export function GetOracles200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOracles200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(OracleFromJSON)),
    };
}

export function GetOracles200ResponseAllOfToJSON(value?: GetOracles200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(OracleToJSON)),
    };
}

