/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Oracle } from './Oracle';
import {
    OracleFromJSON,
    OracleFromJSONTyped,
    OracleToJSON,
} from './Oracle';

/**
 * 
 * @export
 * @interface GetOracles200Response
 */
export interface GetOracles200Response {
    /**
     * 
     * @type {Array<Oracle>}
     * @memberof GetOracles200Response
     */
    data?: Array<Oracle>;
    /**
     * 
     * @type {string}
     * @memberof GetOracles200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetOracles200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetOracles200Response interface.
 */
export function instanceOfGetOracles200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetOracles200ResponseFromJSON(json: any): GetOracles200Response {
    return GetOracles200ResponseFromJSONTyped(json, false);
}

export function GetOracles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOracles200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(OracleFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetOracles200ResponseToJSON(value?: GetOracles200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(OracleToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

