/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex9Response } from './Aex9Response';
import {
    Aex9ResponseFromJSON,
    Aex9ResponseFromJSONTyped,
    Aex9ResponseToJSON,
} from './Aex9Response';

/**
 * 
 * @export
 * @interface GetSortedAex9Tokens200ResponseAllOf
 */
export interface GetSortedAex9Tokens200ResponseAllOf {
    /**
     * 
     * @type {Array<Aex9Response>}
     * @memberof GetSortedAex9Tokens200ResponseAllOf
     */
    data?: Array<Aex9Response>;
}

/**
 * Check if a given object implements the GetSortedAex9Tokens200ResponseAllOf interface.
 */
export function instanceOfGetSortedAex9Tokens200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSortedAex9Tokens200ResponseAllOfFromJSON(json: any): GetSortedAex9Tokens200ResponseAllOf {
    return GetSortedAex9Tokens200ResponseAllOfFromJSONTyped(json, false);
}

export function GetSortedAex9Tokens200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSortedAex9Tokens200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex9ResponseFromJSON)),
    };
}

export function GetSortedAex9Tokens200ResponseAllOfToJSON(value?: GetSortedAex9Tokens200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex9ResponseToJSON)),
    };
}

