/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex9Response } from './Aex9Response';
import {
    Aex9ResponseFromJSON,
    Aex9ResponseFromJSONTyped,
    Aex9ResponseToJSON,
} from './Aex9Response';

/**
 * 
 * @export
 * @interface GetSortedAex9Tokens200Response
 */
export interface GetSortedAex9Tokens200Response {
    /**
     * 
     * @type {Array<Aex9Response>}
     * @memberof GetSortedAex9Tokens200Response
     */
    data?: Array<Aex9Response>;
    /**
     * 
     * @type {string}
     * @memberof GetSortedAex9Tokens200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSortedAex9Tokens200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetSortedAex9Tokens200Response interface.
 */
export function instanceOfGetSortedAex9Tokens200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSortedAex9Tokens200ResponseFromJSON(json: any): GetSortedAex9Tokens200Response {
    return GetSortedAex9Tokens200ResponseFromJSONTyped(json, false);
}

export function GetSortedAex9Tokens200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSortedAex9Tokens200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex9ResponseFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetSortedAex9Tokens200ResponseToJSON(value?: GetSortedAex9Tokens200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex9ResponseToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

