/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Aex141Response } from './Aex141Response';
import {
    Aex141ResponseFromJSON,
    Aex141ResponseFromJSONTyped,
    Aex141ResponseToJSON,
} from './Aex141Response';

/**
 * 
 * @export
 * @interface GetSortedAex141Contracts200Response
 */
export interface GetSortedAex141Contracts200Response {
    /**
     * 
     * @type {Array<Aex141Response>}
     * @memberof GetSortedAex141Contracts200Response
     */
    data?: Array<Aex141Response>;
    /**
     * 
     * @type {string}
     * @memberof GetSortedAex141Contracts200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetSortedAex141Contracts200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetSortedAex141Contracts200Response interface.
 */
export function instanceOfGetSortedAex141Contracts200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSortedAex141Contracts200ResponseFromJSON(json: any): GetSortedAex141Contracts200Response {
    return GetSortedAex141Contracts200ResponseFromJSONTyped(json, false);
}

export function GetSortedAex141Contracts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSortedAex141Contracts200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Aex141ResponseFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetSortedAex141Contracts200ResponseToJSON(value?: GetSortedAex141Contracts200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Aex141ResponseToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

