/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TotalStat } from './TotalStat';
import {
    TotalStatFromJSON,
    TotalStatFromJSONTyped,
    TotalStatToJSON,
} from './TotalStat';

/**
 * 
 * @export
 * @interface GetTotalstats200Response
 */
export interface GetTotalstats200Response {
    /**
     * 
     * @type {Array<TotalStat>}
     * @memberof GetTotalstats200Response
     */
    data?: Array<TotalStat>;
    /**
     * 
     * @type {string}
     * @memberof GetTotalstats200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetTotalstats200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the GetTotalstats200Response interface.
 */
export function instanceOfGetTotalstats200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTotalstats200ResponseFromJSON(json: any): GetTotalstats200Response {
    return GetTotalstats200ResponseFromJSONTyped(json, false);
}

export function GetTotalstats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTotalstats200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TotalStatFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function GetTotalstats200ResponseToJSON(value?: GetTotalstats200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TotalStatToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

