/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transfer } from './Transfer';
import {
    TransferFromJSON,
    TransferFromJSONTyped,
    TransferToJSON,
} from './Transfer';

/**
 * 
 * @export
 * @interface GetTransfers200ResponseAllOf
 */
export interface GetTransfers200ResponseAllOf {
    /**
     * 
     * @type {Array<Transfer>}
     * @memberof GetTransfers200ResponseAllOf
     */
    data?: Array<Transfer>;
}

/**
 * Check if a given object implements the GetTransfers200ResponseAllOf interface.
 */
export function instanceOfGetTransfers200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTransfers200ResponseAllOfFromJSON(json: any): GetTransfers200ResponseAllOf {
    return GetTransfers200ResponseAllOfFromJSONTyped(json, false);
}

export function GetTransfers200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransfers200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TransferFromJSON)),
    };
}

export function GetTransfers200ResponseAllOfToJSON(value?: GetTransfers200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TransferToJSON)),
    };
}

