/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TotalStat } from './TotalStat';
import {
    TotalStatFromJSON,
    TotalStatFromJSONTyped,
    TotalStatToJSON,
} from './TotalStat';

/**
 * 
 * @export
 * @interface GetTotalstats200ResponseAllOf
 */
export interface GetTotalstats200ResponseAllOf {
    /**
     * 
     * @type {Array<TotalStat>}
     * @memberof GetTotalstats200ResponseAllOf
     */
    data?: Array<TotalStat>;
}

/**
 * Check if a given object implements the GetTotalstats200ResponseAllOf interface.
 */
export function instanceOfGetTotalstats200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTotalstats200ResponseAllOfFromJSON(json: any): GetTotalstats200ResponseAllOf {
    return GetTotalstats200ResponseAllOfFromJSONTyped(json, false);
}

export function GetTotalstats200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTotalstats200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TotalStatFromJSON)),
    };
}

export function GetTotalstats200ResponseAllOfToJSON(value?: GetTotalstats200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TotalStatToJSON)),
    };
}

