/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyBlock
 */
export interface KeyBlock {
    /**
     * The beneficiary
     * @type {string}
     * @memberof KeyBlock
     */
    beneficiary?: string;
    /**
     * The block hash
     * @type {string}
     * @memberof KeyBlock
     */
    hash?: string;
    /**
     * The block height
     * @type {number}
     * @memberof KeyBlock
     */
    height?: number;
    /**
     * The info
     * @type {string}
     * @memberof KeyBlock
     */
    info?: string;
    /**
     * The miner public key
     * @type {string}
     * @memberof KeyBlock
     */
    miner?: string;
    /**
     * The nonce
     * @type {string}
     * @memberof KeyBlock
     */
    nonce?: string;
    /**
     * The pow
     * @type {Array<number>}
     * @memberof KeyBlock
     */
    pow?: Array<number>;
    /**
     * The previous block hash
     * @type {string}
     * @memberof KeyBlock
     */
    prevHash?: string;
    /**
     * The previous key block hash
     * @type {string}
     * @memberof KeyBlock
     */
    prevKeyHash?: string;
    /**
     * The state hash
     * @type {string}
     * @memberof KeyBlock
     */
    stateHash?: string;
    /**
     * The target
     * @type {number}
     * @memberof KeyBlock
     */
    target?: number;
    /**
     * The time
     * @type {number}
     * @memberof KeyBlock
     */
    time?: number;
    /**
     * The version
     * @type {number}
     * @memberof KeyBlock
     */
    version?: number;
}

/**
 * Check if a given object implements the KeyBlock interface.
 */
export function instanceOfKeyBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KeyBlockFromJSON(json: any): KeyBlock {
    return KeyBlockFromJSONTyped(json, false);
}

export function KeyBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'beneficiary': !exists(json, 'beneficiary') ? undefined : json['beneficiary'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'info': !exists(json, 'info') ? undefined : json['info'],
        'miner': !exists(json, 'miner') ? undefined : json['miner'],
        'nonce': !exists(json, 'nonce') ? undefined : json['nonce'],
        'pow': !exists(json, 'pow') ? undefined : json['pow'],
        'prevHash': !exists(json, 'prev_hash') ? undefined : json['prev_hash'],
        'prevKeyHash': !exists(json, 'prev_key_hash') ? undefined : json['prev_key_hash'],
        'stateHash': !exists(json, 'state_hash') ? undefined : json['state_hash'],
        'target': !exists(json, 'target') ? undefined : json['target'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function KeyBlockToJSON(value?: KeyBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'beneficiary': value.beneficiary,
        'hash': value.hash,
        'height': value.height,
        'info': value.info,
        'miner': value.miner,
        'nonce': value.nonce,
        'pow': value.pow,
        'prev_hash': value.prevHash,
        'prev_key_hash': value.prevKeyHash,
        'state_hash': value.stateHash,
        'target': value.target,
        'time': value.time,
        'version': value.version,
    };
}

