/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MicroBlock
 */
export interface MicroBlock {
    /**
     * The micro block hash
     * @type {string}
     * @memberof MicroBlock
     */
    hash?: string;
    /**
     * The block height
     * @type {number}
     * @memberof MicroBlock
     */
    height?: number;
    /**
     * The index of the micro-block on the micro-block height, starting from 0
     * @type {number}
     * @memberof MicroBlock
     */
    microBlockIndex?: number;
    /**
     * The pow
     * @type {Array<number>}
     * @memberof MicroBlock
     */
    pofHash?: Array<number>;
    /**
     * The previous block hash
     * @type {string}
     * @memberof MicroBlock
     */
    prevHash?: string;
    /**
     * The previous key block hash
     * @type {string}
     * @memberof MicroBlock
     */
    prevKeyHash?: string;
    /**
     * The state hash
     * @type {string}
     * @memberof MicroBlock
     */
    stateHash?: string;
    /**
     * The time
     * @type {number}
     * @memberof MicroBlock
     */
    time?: number;
    /**
     * The number of transactions
     * @type {number}
     * @memberof MicroBlock
     */
    transactionsCount?: number;
    /**
     * The version
     * @type {number}
     * @memberof MicroBlock
     */
    version?: number;
}

/**
 * Check if a given object implements the MicroBlock interface.
 */
export function instanceOfMicroBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MicroBlockFromJSON(json: any): MicroBlock {
    return MicroBlockFromJSONTyped(json, false);
}

export function MicroBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): MicroBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'microBlockIndex': !exists(json, 'micro_block_index') ? undefined : json['micro_block_index'],
        'pofHash': !exists(json, 'pof_hash') ? undefined : json['pof_hash'],
        'prevHash': !exists(json, 'prev_hash') ? undefined : json['prev_hash'],
        'prevKeyHash': !exists(json, 'prev_key_hash') ? undefined : json['prev_key_hash'],
        'stateHash': !exists(json, 'state_hash') ? undefined : json['state_hash'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'transactionsCount': !exists(json, 'transactions_count') ? undefined : json['transactions_count'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function MicroBlockToJSON(value?: MicroBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'height': value.height,
        'micro_block_index': value.microBlockIndex,
        'pof_hash': value.pofHash,
        'prev_hash': value.prevHash,
        'prev_key_hash': value.prevKeyHash,
        'state_hash': value.stateHash,
        'time': value.time,
        'transactions_count': value.transactionsCount,
        'version': value.version,
    };
}

