/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NameInfo } from './NameInfo';
import {
    NameInfoFromJSON,
    NameInfoFromJSONTyped,
    NameInfoToJSON,
} from './NameInfo';

/**
 * Name
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * 
     * @type {boolean}
     * @memberof Name
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    hash?: string;
    /**
     * 
     * @type {NameInfo}
     * @memberof Name
     */
    info?: NameInfo;
    /**
     * 
     * @type {Array<Name>}
     * @memberof Name
     */
    previous?: Array<Name>;
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    status?: NameStatusEnum;
}


/**
 * @export
 */
export const NameStatusEnum = {
    Name: 'name',
    Auction: 'auction'
} as const;
export type NameStatusEnum = typeof NameStatusEnum[keyof typeof NameStatusEnum];


/**
 * Check if a given object implements the Name interface.
 */
export function instanceOfName(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NameFromJSON(json: any): Name {
    return NameFromJSONTyped(json, false);
}

export function NameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Name {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'info': !exists(json, 'info') ? undefined : NameInfoFromJSON(json['info']),
        'previous': !exists(json, 'previous') ? undefined : ((json['previous'] as Array<any>).map(NameFromJSON)),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function NameToJSON(value?: Name | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'hash': value.hash,
        'info': NameInfoToJSON(value.info),
        'previous': value.previous === undefined ? undefined : ((value.previous as Array<any>).map(NameToJSON)),
        'status': value.status,
    };
}

