/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameInfoOwnership
 */
export interface NameInfoOwnership {
    /**
     * 
     * @type {string}
     * @memberof NameInfoOwnership
     */
    current?: string;
    /**
     * 
     * @type {string}
     * @memberof NameInfoOwnership
     */
    original?: string;
}

/**
 * Check if a given object implements the NameInfoOwnership interface.
 */
export function instanceOfNameInfoOwnership(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NameInfoOwnershipFromJSON(json: any): NameInfoOwnership {
    return NameInfoOwnershipFromJSONTyped(json, false);
}

export function NameInfoOwnershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameInfoOwnership {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'current': !exists(json, 'current') ? undefined : json['current'],
        'original': !exists(json, 'original') ? undefined : json['original'],
    };
}

export function NameInfoOwnershipToJSON(value?: NameInfoOwnership | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current': value.current,
        'original': value.original,
    };
}

