/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Name Transfer
 * @export
 * @interface NameTransfer
 */
export interface NameTransfer {
    /**
     * 
     * @type {string}
     * @memberof NameTransfer
     */
    blockHash?: string;
    /**
     * 
     * @type {number}
     * @memberof NameTransfer
     */
    height?: number;
    /**
     * 
     * @type {object}
     * @memberof NameTransfer
     */
    tx?: object;
}

/**
 * Check if a given object implements the NameTransfer interface.
 */
export function instanceOfNameTransfer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NameTransferFromJSON(json: any): NameTransfer {
    return NameTransferFromJSONTyped(json, false);
}

export function NameTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blockHash': !exists(json, 'block_hash') ? undefined : json['block_hash'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'tx': !exists(json, 'tx') ? undefined : json['tx'],
    };
}

export function NameTransferToJSON(value?: NameTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'block_hash': value.blockHash,
        'height': value.height,
        'tx': value.tx,
    };
}

