/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Resource not found on the API
 * @export
 * @interface NotFoundResponse
 */
export interface NotFoundResponse {
    /**
     * The message of the error raised
     * @type {string}
     * @memberof NotFoundResponse
     */
    error: string;
}

/**
 * Check if a given object implements the NotFoundResponse interface.
 */
export function instanceOfNotFoundResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function NotFoundResponseFromJSON(json: any): NotFoundResponse {
    return NotFoundResponseFromJSONTyped(json, false);
}

export function NotFoundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function NotFoundResponseToJSON(value?: NotFoundResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

