/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The oracle's query and response formats
 * @export
 * @interface OracleExtendsInner
 */
export interface OracleExtendsInner {
    /**
     * The query format
     * @type {string}
     * @memberof OracleExtendsInner
     */
    query: string;
    /**
     * The response format
     * @type {string}
     * @memberof OracleExtendsInner
     */
    response: string;
}

/**
 * Check if a given object implements the OracleExtendsInner interface.
 */
export function instanceOfOracleExtendsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "query" in value;
    isInstance = isInstance && "response" in value;

    return isInstance;
}

export function OracleExtendsInnerFromJSON(json: any): OracleExtendsInner {
    return OracleExtendsInnerFromJSONTyped(json, false);
}

export function OracleExtendsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OracleExtendsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'query': json['query'],
        'response': json['response'],
    };
}

export function OracleExtendsInnerToJSON(value?: OracleExtendsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'query': value.query,
        'response': value.response,
    };
}

