/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedResponse
 */
export interface PaginatedResponse {
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedResponse
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the PaginatedResponse interface.
 */
export function instanceOfPaginatedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedResponseFromJSON(json: any): PaginatedResponse {
    return PaginatedResponseFromJSONTyped(json, false);
}

export function PaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function PaginatedResponseToJSON(value?: PaginatedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'next': value.next,
        'prev': value.prev,
    };
}

