/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchNames200ResponseAllOfDataInner } from './SearchNames200ResponseAllOfDataInner';
import {
    SearchNames200ResponseAllOfDataInnerFromJSON,
    SearchNames200ResponseAllOfDataInnerFromJSONTyped,
    SearchNames200ResponseAllOfDataInnerToJSON,
} from './SearchNames200ResponseAllOfDataInner';

/**
 * 
 * @export
 * @interface SearchNames200Response
 */
export interface SearchNames200Response {
    /**
     * 
     * @type {Array<SearchNames200ResponseAllOfDataInner>}
     * @memberof SearchNames200Response
     */
    data?: Array<SearchNames200ResponseAllOfDataInner>;
    /**
     * 
     * @type {string}
     * @memberof SearchNames200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchNames200Response
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the SearchNames200Response interface.
 */
export function instanceOfSearchNames200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchNames200ResponseFromJSON(json: any): SearchNames200Response {
    return SearchNames200ResponseFromJSONTyped(json, false);
}

export function SearchNames200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchNames200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SearchNames200ResponseAllOfDataInnerFromJSON)),
        'next': !exists(json, 'next') ? undefined : json['next'],
        'prev': !exists(json, 'prev') ? undefined : json['prev'],
    };
}

export function SearchNames200ResponseToJSON(value?: SearchNames200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SearchNames200ResponseAllOfDataInnerToJSON)),
        'next': value.next,
        'prev': value.prev,
    };
}

