/* tslint:disable */
/* eslint-disable */
/**
 * Aeternity Middleware
 * API for [Aeternity Middleware](https://github.com/aeternity/ae_mdw)
 *
 * The version of the OpenAPI document: 1.51.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchNames200ResponseAllOfDataInner } from './SearchNames200ResponseAllOfDataInner';
import {
    SearchNames200ResponseAllOfDataInnerFromJSON,
    SearchNames200ResponseAllOfDataInnerFromJSONTyped,
    SearchNames200ResponseAllOfDataInnerToJSON,
} from './SearchNames200ResponseAllOfDataInner';

/**
 * 
 * @export
 * @interface SearchNames200ResponseAllOf
 */
export interface SearchNames200ResponseAllOf {
    /**
     * 
     * @type {Array<SearchNames200ResponseAllOfDataInner>}
     * @memberof SearchNames200ResponseAllOf
     */
    data?: Array<SearchNames200ResponseAllOfDataInner>;
}

/**
 * Check if a given object implements the SearchNames200ResponseAllOf interface.
 */
export function instanceOfSearchNames200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchNames200ResponseAllOfFromJSON(json: any): SearchNames200ResponseAllOf {
    return SearchNames200ResponseAllOfFromJSONTyped(json, false);
}

export function SearchNames200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchNames200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SearchNames200ResponseAllOfDataInnerFromJSON)),
    };
}

export function SearchNames200ResponseAllOfToJSON(value?: SearchNames200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SearchNames200ResponseAllOfDataInnerToJSON)),
    };
}

